# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: cclint

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  # Non-darwin builds (no signing needed)
  - id: cclint-linux-windows
    main: ./cmd/cclint
    binary: cclint
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/pthm/cclint/internal/version.Version={{.Version}}
      - -X github.com/pthm/cclint/internal/version.Commit={{.Commit}}
      - -X github.com/pthm/cclint/internal/version.Date={{.Date}}

  # Darwin builds with code signing
  - id: cclint-darwin
    main: ./cmd/cclint
    binary: cclint
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/pthm/cclint/internal/version.Version={{.Version}}
      - -X github.com/pthm/cclint/internal/version.Commit={{.Commit}}
      - -X github.com/pthm/cclint/internal/version.Date={{.Date}}
    hooks:
      post:
        - cmd: ./scripts/sign-macos.sh "{{ .Path }}" --notarize
          output: true

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: pthm
    name: cclint
  draft: false
  prerelease: auto
  mode: replace
  name_template: "v{{.Version}}"

homebrew_casks:
  - name: cclint
    repository:
      owner: pthm
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/pthm/cclint"
    description: "A linter for Claude Code configurations"
    license: "MIT"
